name: release-please

on:
  push:
    branches:
      - main
      - "v*-branch"

permissions:
  contents: write
  pull-requests: write

jobs:
  handle-commit:
    name: Handle new commit
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release-new-version:
    name: Release new version
    needs: handle-commit
    runs-on: ubuntu-latest
    if: ${{ needs.handle-commit.outputs.release_created }}
    env:
      ZMK_RELEASE_PLEASE_TOKEN: ${{ secrets.ZMK_RELEASE_PLEASE_TOKEN }}
      VERSION: v${{ needs.handle-commit.outputs.major }}.${{ needs.handle-commit.outputs.minor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create major.minor branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b $VERSION
          git push origin $VERSION

